BeamApp/BeamApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('landing/', include('landing.urls', namespace='landing')),
    path('account/', include('account.urls')),
    path('', include('about.urls', namespace='about')),
    path('work/', include('work.urls', namespace='work')),
    path('spring/', include('spring.urls', namespace='spring')),
    path('chat/', include('chat.urls', namespace='chat')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BeamApp/about/urls.py
from django.urls import path
from . import views
app_name = 'about'
urlpatterns = [
    path('', views.aboutpage, name='aboutpage'),
]

BeamApp/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('forumpages', views.forum_pages, name='forumpages'),
    path("", views.forum, name="forum"),
    path("discussion/<int:myid>/", views.discussion, name="Discussions"),
    # path('<int:room_id>/', views.chat_room,
    #      name='chat_room'),
    # path('join-room/',
    #         views.JoinRoomView.as_view(),
    #         name='join_room'),
]

BeamApp/spring/urls.py
from django.urls import path
from . import views
app_name = 'spring'
urlpatterns = [
    path('', views.create, name='spring'),
]

BeamApp/work/urls.py
from django.urls import path
from . import views
app_name = 'work'
urlpatterns = [
    path('', views.create, name='work'),
]

BeamApp/templates/base.html
<!--{% load static %}-->
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>

<body>
  <nav class="navbar navbar-dark navbar-expand-lg bg-success bg-gradient">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url "about:aboutpage" %}">Балка Онлайн</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="calculatorDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Калькулятор
            </a>
            <ul class="dropdown-menu" aria-labelledby="calculatorDropdown">
              <li><a class="dropdown-item" href="{% url "work:work" %}">Стержневая система</a></li>
              <li><a class="dropdown-item" href="{% url "spring:spring" %}">Пружинная система</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "chat:forum" %}">Форум</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "account" %}">Аккаунт</a>
          </li>
        </ul>
        {% endif %}
        <span class="text-light">
          {% if request.user.is_authenticated %}
          Здравствуйте, {{ request.user.first_name|default:request.user.username }}!
          <a href="{% url "logout" %}" class="btn btn-outline-light me-md-2" role="button">Выйти</a>
          {% else %}
          <a href="{% url "login" %}" class="btn btn-outline-light me-md-2" role="button">Войти</a>
          {% endif %}
        </span>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    {% block contents %}
    {% endblock %}
  </div>

  <!-- Footer -->
  <footer class="bg-secondary text-white text-center text-md-start">
    <!-- Grid container -->
    <div class="container-fluid p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">Балка Онлайн</h5>
          <p>Инновационный инженерный калькулятор, разработанный студентами МГТУ им. Н. Э. Баумана.</p>
          <p>Позволяет находить оптимальные параметры модульной балки.</p>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Быстрый старт</h5>
          <ul class="list-unstyled mb-0">
            <p>Начни пользоваться калькулятором уже сейчас!</p>
            <a class="btn" href="/account" target="_blank">Зарегистрироваться</a>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-0">Контакты</h5>
          <ul class="list-unstyled">
            <li>
              <a href="mailto:info@domain.com" title="glorythemes">beamapp@bk.ru</a>
            </li>
            <li class="">
              <a title="youtube" target="_blank" href="https://youtube.com"><img width="50" height="50" src="https://img.icons8.com/ios/50/FFFFFF/youtube-play--v1.png" alt="youtube-play--v1"/></a>
            </li>
            <li class="">
              <a title="VK" target="_blank" href="https://vk.com"><img width="50" height="50" src="https://img.icons8.com/ios/50/FFFFFF/vk-com.png" alt="vk-com"/></a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center fluid p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 BeamApp
    </div>
  </footer>

  {% bootstrap_javascript %}

</body>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  {% block js %} {% endblock %}
</html>